## Library Imports

In [154]:
import requests
import json
import pandas as pd

## Importing Our List of App Market ID

In [155]:
stocks = pd.read_csv('Vungle ad_transactions 2021-10-05T1747-android - 副本.csv')

In [156]:
marketID=stocks['marketid']

## Adding columns to a Pandas DataFrame

In [157]:
my_columns = ['marketid', 'AppAdsUrl']

##  Looping Through The MarketID in Our List of CSV
1. If dataJson[1] is not work, try dataJson[0]
2. Change platform iOS/Android before run

In [159]:
final_dataframe = pd.DataFrame(columns = my_columns)

for marketid in stocks['marketid']:
    api_url = f'http://api.adtimizer.co/ios/app-ads-txt?id={marketid}'
    data = requests.get(api_url)
    if data.status_code == 200:
        dataJson=data.json()
        final_dataframe = final_dataframe.append(
                            pd.Series([
                                        marketid,
                                        dataJson[0]['AppAdsUrl'],],
                                        index = my_columns), 
                                        ignore_index = True)

    elif data.status_code == 204:
       
        final_dataframe = final_dataframe.append(
                            pd.Series([
                                        marketid,
                                        data.status_code,],
                                        index = my_columns), 
                                        ignore_index = True)
    
final_dataframe

      marketid     AppAdsUrl
0   1483058899           204
1    880178264           204
2    664370402           204
3    363282253           204
4   1442895889           204
5   1460564684           204
6   1234436634           204
7    501306812           204
8   1449164533           204
9   1176156412           204
10  1319179770           204
11  1586816456           204
12  1102002812           204
13   855627886           204
14  1265838130           204
15  1563239332           204
16  1583177659           204
17  1146128499           204
18  1345968745           204
19  1322366209           204
20  1581753546           204
21  1471527199           204
22  1208561922           204
23   963067330           204
24  1567885747           204
25  1556070521           204
26  1004216430           204
27  1174766830           204
28  1250312807       xvpn.io
29  1572797307           204
30   448999087           204
31  1419734728           204
32  1575647531  mondayoff.me
33  1214763610    mytona.com

## pandas.DataFrame.to_csv

In [ ]:
final_dataframe

In [135]:
final_dataframe.to_csv("android3.csv")